server:
  name: user-edge-service
  port: 8082

thrift:
  user:
    service:
      ip: 127.0.0.1
      port: 7911
  message:
    service:
      ip: 127.0.0.1
      port: 9090

#redis config
spring:
  redis:
    host: localhost
    port: 6379