eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
server:
  port: 9011
spring:
  application:
    name: course-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_course?useSSL=false
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
    username: root
thrift:
  service:
    ip: 127.0.0.1
    port: 7911
