service:
  name: user-thrift-service
  port: 7911

#dataSource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_user?useSSL=false
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver